### ISSUE TITLE
PlexConnect not starting with 5.3 jailbreak python errors (with fix)

### ISSUE THREAD

**Issue by scuffe82** [iBaa/PlexConnect#272]
on a fresh jailbreak of my appletv2 plexconnect wouldn't start automatically The logs showed 

/Applications/PlexConnect/support/aTV_jailbreak/PlexConnect.bash: line 42: ../../PlexConnect.py: No such file or directory

To fix this I did the following

chmod +x  /Applications/PlexConnect/PlexConnect.py
chmod +x /Applications/PlexConnect/support/aTV_jailbreak/PlexConnect.bash

I also had to add the following line to PlexConnect.bash

APPDIR="/Applications/PlexConnect"

And had to edit the last line from 
./${APPNAME}
to
python2.7 ${APPDIR}/${APPNAME}

Once i did this plexconnect would start on boot of the appletv.

**Comment by wahlmanj** [comment]
I have seen a similar issue debugging the original method on my end where other users did not. I belive it is due to either a hardware difference in the aTV2's or other firmware from alternative apple sources but I'm leaning on hardware. I have made a modified method based on baa's original method if you want to give it a try, it works very well for me and automates the entire modified method:

https://forums.plex.tv/index.php/topic/88905-plexconnect-on-atv2jailbroken-launchctl/page-18
