### ISSUE TITLE
ATV not connecting to Plex Connect

### ISSUE THREAD

**Issue by SwissTony77** [iBaa/PlexConnect#366]
Hi, I have browsed the issues and tried to self fix but no luck. Please help if you are able to do so.

Issue is that on the ATV I can see the PMS but the libraries are not showing.
Details as required

PlexConnect installed on 192.168.1.3 - Mac Mini OSX 10.10.4
Your ATV model (2 or 3) and firmware version (found under the ATV settings > general > about > Apple TV software): ATV 3, Firmware 6.2 (6698.99.50.31)
The DNS server set on the ATV (found under the ATV settings > general > network > DNS): DNS 192.168.1.3
The local IP address of the device that PlexConnect is installed on: 192.168.1.3
The device and operating system (including version number) that PlexConnect is installed on: Mac Mini OSX 10.10.4
The device and operating system (including version number) that the Plex media server (PMS) is installed on: Mac Mini OSX 10.10.4
The Plex media server (PMS) version number you are running (do not put 'latest'): 2.4.9
The local IP address of the device that the Plex media server (PMS) is installed on: 192.168.1.3
The PlexConnect version number. If using Github source then a time and date of download (look at the creation date of the folder) and if you are using any non-standard setup or a fork. : Creation Date 11 Jan 2015, version 0.5-dev
The contents of your 'Settings.cfg' file (this is created at first clean shutdown of PlexConnect, using CTR+c)
[PlexConnect]
enable_plexgdm = True
ip_pms = 192.168.1.3
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
loglevel = High
logpath = .
A detailed description of the issue (the clearer you can make this the better): Opening Plex on the ATC I see the error no libraries available, in the log it shows that "We failed to reach a server. Reason: Unauthorized" Plex works perfectly using PHT which is also installed on the mac mini

Ensure you post your 'PlexConnect.log' file to pastebin and post the link ('PlexConnect.log' is located in your PlexConnect folder). If possible, follow these steps to create a "more detailed fresh" one: 

Link is http://pastebin.com/X4xS6SAk

**Comment by iBaa** [comment]
Using PlexHome? Or "require authentication" on PMS? PlexConnect currently does not support PMS https communication as well.
Your log indicates an older version... please update, and try again - with respect to my earlier questions, you might have to sign in to myPlex.

**Comment by tadgy** [comment]
I'm experiencing the same issues as the original poster, and can confirm that this appears to be as a result of upgrading the PMS version to a version beyond 0.9.12.4 - since my PlexConnect set up was operating perfectly fine until my upgrade of PMS today.

I am running the 0-5dev 020615 version of PlexConnect on my AppleTV, PMS version 0.9.12.8 on OSX, and have logged into MyPlex on both the server and in PlexConnect.  I had additionally added my network range to the list of networks in PMS that do not require authentication.  No joy with any of these settings.

I do not have PlexHome or a PlexPass and can't find any specific options in the PMS settings to "require authorisation" or not (but I assume this will have been nullified by my deliberately adding my LAN network range to the list of networks to NOT require auth).

Please can you advise further on how to correct these issues?  I suspect more and more people are going to be faced with this as they upgrade their PMS version.

**Comment by SwissTony77** [comment]
Hi, Sorry I didn't update this thread, I have been out of town. Essentially it wasn't anything to do with versions. I had logged into my account on the PMS, logging out fixed the issues and I am now able to access plex from the ATV.
