### ISSUE TITLE
ATV 7.3 firmware

### ISSUE THREAD

**Issue by fatfreddyone** [iBaa/PlexConnect#369]
Hello
is someone already test plexconnect with 7.3 firwmare ?
thanks

**Comment by feld** [comment]
I can't find any information anywhere on 7.3. If you have some release notes etc on it please let me know.

**Comment by wahlmanj** [comment]
aTV3 firmare has been discontinued likely due to aTV4 TVOS:

https://en.wikipedia.org/wiki/IOS_version_history

**Comment by aidasan** [comment]
Hello
I don't think this is true.
The ATV FW and iOS are different but they have put both inside the iOS 8.3 ...

Since there is no info on the apple official page I will put some reserve on this news.

**Comment by wahlmanj** [comment]
Well I would love to see this also but I always go to that site to see when firmwares are discontinued. aTV4 is the future now, I highly doubt they are going to update the iOS when they now have a new aTV. iOS & aTV FW is actually the same thing, it's strange how they name it on aTVs and may cause confusion but since it was updated last in April for the aTV3 7.2 (8.3) and often prior good chance that ship has sailed:

https://www.theiphonewiki.com/wiki/SHSH
