### ISSUE TITLE
Thanks for this great library

### ISSUE THREAD

**Issue by liuxuan30** [iBaa/PlexConnect#376]
I have known this library about two years I guess, and it introduces Plex to me, and I bought a lifepass a long time ago.

I have been using it for many times, and it works so awesome. Though the new ATV is coming out and enable us to put apps on ATV, I guess Plex is going to release a ATV app. So I think it's the time for me to thank all of you for this amazing library!

**Comment by Rycochet** [comment]
Unless they allow apps on the old hardware I'm sticking to this - not least because the new remote is seriously ugly, I have no interest in voice control, and this does exactly what I need - it's not worth spending money to buy a new ATV purely for watching Plex as the TV games market is completely saturated already ;-)
