### ISSUE TITLE
Suggestion: App for new Apple TV

### ISSUE THREAD

**Issue by clemens-schulz** [iBaa/PlexConnect#393]
Trailers no longer exist on the new Apple TV, but we can write our own apps. Apple provides a framework for TVML, so it should be very easy to write a simple client app for PlexConnect.
Is anyone already looking into this or is there a reason this wouldn't work?

**Comment by Rycochet** [comment]
From what I read about it, they changed everything about how it works - it's no longer just an XML reading frontend, which means that minor rewrites of the data direct from Plex isn't enough to get it working - Plex themselves are doing an App for it, in fact the most recent Plex server for my NAS was to fix something related to their new App...

**Comment by carlsteinhilber** [comment]
Indeed.

No reason to write an "app for PlexConnect" when the ATV app can connect directly to the Plex server itself.


PlexConnect is awesome, and I'll continue to use it as long as I'm able because I doubt I'll buy a new gen ATV or ever update the one I have if I can help it  But for those on the new system/architecture, PlexConnect would be an unneeded middleman in the process.




Sent by Outlook for Android





On Fri, Oct 30, 2015 at 5:53 AM -0700, "Rycochet" <notifications@github.com> wrote:












From what I read about it, they changed everything about how it works - it's no longer just an XML reading frontend, which means that minor rewrites of the data direct from Plex isn't enough to get it working - Plex themselves are doing an App for it, in fact the most recent Plex server for my NAS was to fix something related to their new App...

**Comment by bakman2** [comment]
There is an app for appletv that works with plex: [simplex](https://www.youtube.com/watch?v=9lkcDwv2x1A)
And an official Plex app is currently pending approval.

**Comment by iBaa** [comment]
Yeah - closing this thread is ok. I guess a trailers emulation to let PlexConnect run is the last thing we need.
There are more options available right now, just read the forums.
But then, don't throw PlexConnect to far away: A PlexConnectApp anybody? :-D

**Comment by Rycochet** [comment]
I'm planning to stick to my classic aTV - no interest in voice control or some stupid touchpad (have you ever tried those things on OSX? They're dire for simple controls) - literally the only benefit to the new one is being Bluetooth rather than IR... As for the interface - I love the new iOS apps, but something like that on the TV wouldn't be as useful for our watching habits ;-)

So in my household at least PlexConnect is here to stay :-)

**Comment by bakman2** [comment]
Actually, I have...for the last 5 years, and they work flawless and fantastisc, haven't touched a mouse since.
So I am not sure what I call "stupid". And the apps will become very usefull, depending on your lifestyle.

**Comment by iBaa** [comment]
Just for the record: https://forums.plex.tv/discussion/191385/plexconnect-works-fine-with-the-new-appletv
But then I don't really see the point, if we can launch a native app without DNS hack on that thing.

**Comment by clemens-schulz** [comment]
Good to know. The Trailers app is only available in the US App Store, so I didn't know it still existed.

**Comment by iBaa** [comment]
More heads up:
https://github.com/iBaa/PlexConnectApp
Not sure, where this all might lead us... :-D

**Comment by bakman2** [comment]
Ibaa, nice! how can it be tested? Does it go on atv? Or do you need an paid dev account for ot?

**Comment by iBaa** [comment]
Yep, it is supposed to run on AppleTV4, no other host needed. For developing purposes you need OSX/XCode. So far I have run it only in the simulator, no idea how it will work on the real hardware.
The paid dev account is - as far as understand - only needed for pushing it to/through the AppStore.

**Comment by TheWoollyBully** [comment]
You need a paid dev account in order to run the code on actual devices to test beyond the simulator.

**Comment by iBaa** [comment]
Huh? From your link:
"You can launch your app on a device using a free Apple ID account, ..."

**Comment by TheWoollyBully** [comment]
I couldn't get it to work so I was under the impression it needed parts only available to paid devs. 
"You can launch your app on a device using a free Apple ID account, but the capabilities available to your app depends on the platform and your Apple Developer Program membership, described in Supported Capabilities."
