### ISSUE TITLE
ATV sees files and acts like it is going to play then just pauses

### ISSUE THREAD

**Issue by camrun91** [iBaa/PlexConnect#477]
I had Plexconnect working fine then I had to reset the Apple TV as it was acting really odd. I set up the DNS and the custom playback quality for transcoding. The ATV sees the server and all files fine. it even acts like it is playing fine. The issue is the video never plays it is transcoding as I can see the buffer building out. It just stays paused. If I hit play it will act like it is going to then pause again. It is acting like it is trying to buffer but its not actually buffering. If I look on the plex status it shows transcode and throttled meaning it has buffered enough. I can get logs for plex and plex connect if needed.

**Comment by Jabigb** [comment]
That sounds like it's it's the same as what mines doing. Have you been able to fix it?

**Comment by CatFisce** [comment]
This might be the same issue as #476. On your ATV try setting dolby digital to auto or ON

**Comment by moodyblue** [comment]
Please test with https://github.com/moodyblue/PlexConnect.git

If successfull I will ask roidy to commit to master

**Comment by camrun91** [comment]
That did fix it for me @moodyblue

**Comment by marr** [comment]
@moodyblue I am seeing transcoding and non-digital playback with this sha.

**Comment by moodyblue** [comment]
@marr tvOS profile was developed for ATV4. tvOS was recently changed to allow EAC3, which is supported by the ATV4 but not by the ATV2/3. That's why we can't use it anymore for ATV2/3. Subtitles require transcoding unless they are srt external AND in PlexConnect settings you have "subtitlerenderer = iOS, PMS"

In the PMS log, if you have debug active, you will have a line starting with "reached decision" that will tell you what is transcoded, and is being passed "as-is" to tha ATV.

**Comment by marr** [comment]
Thanks @moodyblue I will check the `subtitlerenderer` setting on plexconnect. ATV3 still supports DTS[-ES], correct?

**Comment by moodyblue** [comment]
@marr I don't see DTS supported by the ATV3 in its specs https://support.apple.com/kb/SP648?viewlocale=en_US&locale=pt_PT

**Comment by moodyblue** [comment]
My repo has been merged with iBaa's.

**Comment by moodyblue** [comment]
Please close your issue. It has been solved with the latest commit.
