### ISSUE TITLE
PlexConnect DNSServer shuts down when host detected by NetAdmin Pro on Mac

### ISSUE THREAD

**Issue by thenib** [iBaa/PlexConnect#558]
When the host running PlexConnect gets detected by NetAdmin Pro app on a Mac the PlexConnect DNSServer shuts down

**Comment by moodyblue** [comment]
Is PlexConnect running in the same Mac as NetAdmin Pro ?

**Comment by thenib** [comment]
Yeah it is

**Comment by moodyblue** [comment]
PlexConnect needs port 53/tcp, if anything is conflicting with this you need to use another DNS service

**Comment by thenib** [comment]
There’s nothing else on the raspberry pi conflicting with the port (where PlexConnect is running), and NetAdmin Pro is an app for scanning the network for hosts and services available on those hosts which is running on a Mac, when the raspberry pi hosting PlexConnect is detected and port 53 is also detected, that’s when the “DNSServer Shutting down” occurs. This isn’t a port conflict on one device, it’s 2 separate devices in this case, sorry that wasn’t clear in my initial post.

**Comment by moodyblue** [comment]
I'm sorry but we can't change DNSServer. We don't know how to do it. But you can install another DNS server in the PI, or a dnsmasq service, and modify `Settings.cfg` so that PlexConnect doesn't start its own DNS service.

The only purpose of DNSServer is to intercept DNS requests, route trailer ones to WebServer (PlexConnect service), and route the rest to a real DNS server. This can be done easily with dnsmasq or another DNS server.

**Comment by thenib** [comment]
Thanks for that, much appreciated
