### ISSUE TITLE
ATV3 - Trailers

### ISSUE THREAD

**Issue by sasagr** [iBaa/PlexConnect#565]
Plex Connect
Youtube: No trailer info available

This is the message I get when I try to play the trailer of a movie on my plex connect with ATV3 jb.
I have a plex pass so trailer should be available to me.
Am I missing some setting?

**Comment by moodyblue** [comment]
PlexConnect downloads its own trailers, development ended before Plex announced trailers, so I doubt that PlexConnect supports them. What happens, in the same movie, if you use an official Plex client, such as Plex/Web ?

**Comment by moodyblue** [comment]
There are several Plex features not implemented in PlexConnect https://forums.plex.tv/t/plexconnect-faqs/210620#Q5

Are you a developer ? Can you contribute to PlexConnect ?

**Comment by sasagr** [comment]
> PlexConnect downloads its own trailers, development ended before Plex announced trailers, so I doubt that PlexConnect supports them. What happens, in the same movie, if you use an official Plex client, such as Plex/Web ?

In official Plex clients trailers work

**Comment by sasagr** [comment]
> There are several Plex features not implemented in PlexConnect https://forums.plex.tv/t/plexconnect-faqs/210620#Q5
> 
> Are you a developer ? Can you contribute to PlexConnect ?

No. I m not a developer

**Comment by fortiko** [comment]
Just started using PlexConnect last week: fantastic job!

@sasagr  @moodyblue  I have also just come across this broken trailer functionality. In a nutshell, the parsing logic in XMLConverter.py needs to be updated to the new YouTube "get_video_info" that is returned by https://www.youtube.com/get_video_info?html5=1&video_id=' + id

I include my adjustments below (additional JSON parsing basically). As a side effect, the new code tries to obtain the URL for the "medium" quality for all trailers (itag=18, where available), and if there is also a 720p version (stag=22) it upgrade to that one instead of the medium quality one. The old code always shone the "medium" version.


# git diff -u XMLConverter.py
`diff --git a/XMLConverter.py b/XMLConverter.py
index 67f21d3..6c9b2da 100755
--- a/XMLConverter.py
+++ b/XMLConverter.py
@@ -22,7 +22,7 @@ import traceback
 import inspect
 import string, random
 import copy  # deepcopy()
-
+import json
 import datetime

 try:
@@ -219,16 +219,21 @@ def XML_PMS2aTV(PMS_address, path, options):
         info = urllib2.urlopen("https://youtube.com/get_video_info?video_id=" + trailerID).read()
         parsed = urlparse.parse_qs(info)

-        key = 'url_encoded_fmt_stream_map'
+        key = 'player_response'
         if not key in parsed:
             return XML_Error('PlexConnect', 'Youtube: No Trailer Info available')
-        streams = parsed[key][0].split(',')
+        streams_dict = json.loads(parsed[key][0])
+        streams = streams_dict['streamingData']['formats']

         url = ''
         for i in range(len(streams)):
-            stream = urlparse.parse_qs(streams[i])
-            if stream['itag'][0] == '18':
-                url = stream['url'][0]
+            stream = streams[i]
+            # 18: "medium", 22: hd720
+            if stream['itag'] == 18:
+                url = stream['url']
+            # if there is also a "22" (720p) stream, let's upgrade to that one
+            if stream['itag'] == 22:
+                url = stream['url']
         if url == '':
             return XML_Error('PlexConnect','Youtube: ATV compatible Trailer not available')`

**Comment by fortiko** [comment]
In addition some details on the itag codes 18 and 22 used above, they are probably as good as it gets regarding quality while maintaining compatibility with the AppleTV:

(Source: https://gist.github.com/Marco01809/34d47c65b1d28829bb17c24c04a0096f)

# Legacy (non-DASH)



Code | Container | Video Codec | Video Res. | Audio Codec | Audio Bitrate | Still used?
-- | -- | -- | -- | -- | -- | --
18 | MP4 | H.264 | 360p | AAC | 96 Kbps | Yes
22 | MP4 | H.264 | 720p | AAC | 192 Kbps | Yes

**Comment by moodyblue** [comment]
Thanks a lot. I've tried to apply your proposed changes but it gives an error
```
Mar 28,2020 11:13:52 WebServer: Internal Server Error:
Traceback (most recent call last):
  File "/Applications/PlexConnect/WebServer.py", line 248, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/Applications/PlexConnect/XMLConverter.py", line 234, in XML_PMS2aTV
    url = stream['url']
KeyError: 'url'
```
It would be great if you could create a fork in github, apply your changes, test them, and submit a pull request

**Comment by fortiko** [comment]
@moodyblue done: https://github.com/iBaa/PlexConnect/pull/573

**Comment by moodyblue** [comment]
Thanks a lot, but still the same error. I've tested on:

ATV3 - python 2.7.6
Windows 64-bit - python 2.7.17

**Comment by sasagr** [comment]
it works fine with me, Python 2.7.6 installed on my ATV3

**Comment by fortiko** [comment]
@moodyblue could perhaps log what the variable stream contains for your scenario, and why it doesn't have an index "url"? What is the video/trailer ID you are working with? For me, this works for any movie I pick (accessing YouTube from Spain).
