### ISSUE TITLE
Can we can a new DSM 6.x package for PlexConnect 0.7.4?

### ISSUE THREAD

**Issue by virtualex-itv** [iBaa/PlexConnect#605]
Hello - great job on PlexConnect but I noticed the most recent package for DSM is behind at v0.7.1.  Is it possible to create a package and add it to the releases for v0.7.4 please?  Would be awesome if this were consistent with each release.  Thanks much!

**Comment by moodyblue** [comment]
Souldn't be difficult but I no longer have a Syno to test. Can I create a package and send it to you for testing ?

**Comment by virtualex-itv** [comment]
> Souldn't be difficult but I no longer have a Syno to test. Can I create a package and send it to you for testing ?

absolutely!

**Comment by moodyblue** [comment]
Package included in V0.7.4, can you pls test ?

**Comment by virtualex-itv** [comment]
> Package included in V0.7.4, can you pls test ?

testing now, but seems to show up as v0.7.1 after selecting the file.  Can you update so it shows the correct version and I'll test?

![2021-07-29_15-00-07](https://user-images.githubusercontent.com/12056704/127550801-242818f6-c0fe-4024-a3b0-55bb565b9c18.png)

**Comment by moodyblue** [comment]
Updated, pls try again

**Comment by virtualex-itv** [comment]
> Updated, pls try again

It installed fine but when I test WSJ on an ATV3, it doesn't connect to PlexConnect.  Anything I can provide to assist you in troubleshooting?

**Comment by moodyblue** [comment]
Are you able to SSH into your NAS ? If yes pls post the contents of `/usr/local/plexconnect/share/PlexConnect/log/PlexConnect.log`

**Comment by virtualex-itv** [comment]
> Maybe a reboot is necessary.
> 
> Are you able to SSH into your NAS ? If yes pls post the contents of `/usr/local/plexconnect/share/PlexConnect/logs/PlexConnect.log`

hrm...doesn't seem like I have a `logs` folder present...

```console
ls /usr/local/plexconnect/share/PlexConnect/
assets           ATVSettings.pyc  DNSServer.py   Localize.py        PILBackgrounds.pyc  PlexConnect_daemon.bash  PlexConnect.pyc            README.md     Settings.pyc  support      WebServer.py     XMLConverter.pyc
ATVSettings.cfg  Debug.py         DNSServer.pyc  Localize.pyc       PlexAPI.py          PlexConnect_daemon.py    plexconnect.service        Settings.cfg  Subtitle.py   Version.py   WebServer.pyc
ATVSettings.py   Debug.pyc        License.txt    PILBackgrounds.py  PlexAPI.pyc         PlexConnect.py           PlexConnect_WinService.py  Settings.py   Subtitle.pyc  Version.pyc  XMLConverter.py```

**Comment by moodyblue** [comment]
Maybe `/usr/local/plexconnect/var/PlexConnect.log`

Also pls post `Settings.cfg`

**Comment by virtualex-itv** [comment]
`PlexConnect.log`
```
Jul 30,2021 05:42:58 PlexConnect: Started
Jul 30,2021 05:42:58 PlexConnect: Version: 0.7.4-210621
Jul 30,2021 05:42:58 PlexConnect: Python: 2.7.18 (tags/DSM6-2-25482-200701:af4aa2a, Mar  4 2021, 18:10:30)
[GCC 4.9.3 20150311 (prerelease)]
Jul 30,2021 05:42:58 PlexConnect: Host OS: linux2
Jul 30,2021 05:42:58 PlexConnect: PILBackgrounds: Is PIL installed? False
Jul 30,2021 05:42:58 PlexConnect: IP_self: 10.0.0.22
Jul 30,2021 05:42:58 DNSServer: Started
Jul 30,2021 05:42:58 DNSServer: Intercept Atv Icon: Enabled
Jul 30,2021 05:42:58 DNSServer: Prevent Atv Update: Enabled
Jul 30,2021 05:42:58 DNSServer: ***
Jul 30,2021 05:42:58 DNSServer: DNSServer: Serving DNS on 10.0.0.22 port 53.
Jul 30,2021 05:42:58 DNSServer: ***
Jul 30,2021 05:42:58 WebServer: Started
Jul 30,2021 05:42:58 WebServer: ***
Jul 30,2021 05:42:58 WebServer: WebServer: Serving HTTP on 10.0.0.22 port 81.
Jul 30,2021 05:42:58 WebServer: ***
Jul 30,2021 05:42:58 WebServer: Started
Jul 30,2021 05:42:58 WebServer: ***
Jul 30,2021 05:42:58 WebServer: WebServer: Serving HTTPS on 10.0.0.22 port 444.
Jul 30,2021 05:42:58 WebServer: ***
```
`Settings.cfg`
```
[PlexConnect]
enable_plexgdm = True
ip_pms = 0.0.0.0
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 10.0.0.30
prevent_atv_update = True
intercept_atv_icon = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
use_custom_dns_bind_ip = False
custom_dns_bind_ip = 0.0.0.0
hosttointercept = video-api-secure.wsj.com
icon = movie-trailers
certfile = /usr/local/plexconnect/etc/certificates/marketwatch.pem
port_webserver = 81
enable_webserver_ssl = True
port_ssl = 444
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
fanart_quality = High
loglevel = Normal
logpath = /usr/local/plexconnect/var
```

**Comment by moodyblue** [comment]
Logs and Settings seems ok, apart from a minor error `icon = movie-trailers` and should be `icon = com.wsjlive.appletv.v2`, but this only affects the plex icon, in case you want to replace the WSJ icon by the Plex one.

What happens if you use Netflix, Podcasts or Radio ? Does it work ? This new install may have replaced your existing certs, so probably you need to remove certs from the ATV3 and load them again specifying `http://10.0.0.22/marketwatch.cer`

Is `10.0.0.30` the address of your router ? Or do you have a DNS service running on that ip ?

**Comment by virtualex-itv** [comment]
`.30` is a DNS service I have running.

I edited the `Settings.cfg` file and changed to `icon = com.wsjlive.appletv.v2`.

I've also removed the cert and tried to reload again specifying `http://10.0.0.22/marketwatch.cer` & `http://video-api-secure.wsj.com/marketwatch.cer` but it failed to install either one.

**Comment by moodyblue** [comment]
> `.30` is a DNS service I have running.
In that case, if you also use the ATV for any other apps, it may be preferrable to disable PlexConnect's DNS service and parametrize your DNS to redirect `video-api-secure.wsj.com` to `10.0.0.2`
> I've also removed the cert and tried to reload again specifying `http://10.0.0.22/marketwatch.cer` & `http://video-api-secure.wsj.com/marketwatch.cer` but it failed to install either one.
First I need to know if other apps (such as podcasts or radio) are working.

**Comment by virtualex-itv** [comment]
yes, all other apps work fine it seems.

**Comment by moodyblue** [comment]
What is the DNS coded in the ATV ? 22 or 30 ?

**Comment by virtualex-itv** [comment]
.22

**Comment by moodyblue** [comment]
PlexConnect has two services, DNS and HTTP. If the ATV uses .22 as DNS and other apps are working this means that DNS service is working.

The problem is the HTTP service. It may not be easy to diagnose, but first pls open your browser and try to open `http://10.0.0.22:81` and `https://10.0.0.22:444`.

**Comment by virtualex-itv** [comment]
is it recommended to use the DNS service?  I've fully uninstalled PC from my Syno and am reinstalling it but chose not to install the DNS service.  What do I need to configure in this case in the System.cfg?

**Comment by moodyblue** [comment]
Your problem is with the HTTP service. Let's try to fix this first. It's a good idea to remove and install PlexConnect using the DNS service and then use your browser to open http://10.0.0.22:81 and https://10.0.0.22:444.

**Comment by virtualex-itv** [comment]
ok after reinstalling, installing DNS service, resetting ATV and pointing to DNS on Syno and adding in the cert, it now appears to be working fine.

However, I couldn't get the WSJ icon to switch to the Plex icon after updating the .cfg and i noticed that the cover art for all movies/shows are blank.

Any ideas on how to resolve both?

**Comment by moodyblue** [comment]
Good.
1) To have the Plex icon instead of the WSJ one you have to stop PlexConnect, modify `Settings.cfg` so that `icon = com.wsjlive.appletv.v2`, start PlexConnect, and then [follow the wiki](https://github.com/iBaa/PlexConnect/wiki/Changing-the-Trailer-app-icon)
2) Cover art blank - did you login PlexConnect to plex.tv ? You need to do this in the screen

**Comment by virtualex-itv** [comment]
ahh ok, maybe i missed a step, i did also sign in to plex.tv but cover art is still missing. I'll need to reset the ATV again to factory default, and then after i plug in the network cable, i point to the Syno again as DNS and re-add the cert, and all should work as expected?

**Comment by moodyblue** [comment]
For the plex icon yes

**Comment by moodyblue** [comment]
For cover art do you mean posters or fanart not appearing ? For the later you need to install `Python Module` from the Syno repository.

**Comment by virtualex-itv** [comment]
Yes that is what I am referring to.  I do have python installed, it used to show the posters but no longer does and I believe there was an issue raised for that before as well.

Also, since I am installing PC on a Synology, I don't understand how the Plex icon will update if it's not connected to the Plex post-reset of the ATV.

**Comment by moodyblue** [comment]
For the plex icon to update correctly you need to have communications between the Syno and the ATV, but none to the outside world. After assuring this, reset the ATV to factory so that it boots showing only Computers and Settings. Then change the DNS to 10.0.0.22 and rebbot the ATV. It will fetch the plex icon (but will not show it). Then connect your LAN to the ethernet and reboot the ATV again, This time it will show the plex icon.

**Comment by virtualex-itv** [comment]
ok understood, waiting for an update to finish applying so that it will reset to factory defaults...will update this comment shortly

**Comment by virtualex-itv** [comment]
Ok so I am at the part where I need to configure DNS but how can I set this manually if no LAN cable is plugged in and I'm not connected to wi-fi?  I do not see any option to configure it

**Comment by moodyblue** [comment]
1) Uninstall PlexConnect
2) Install PlexConnect (with DNS) and change `icon ` parameter
3) Connect ATV and Syno to the same switch (same VLAN)
4) Unplug from the switch the cable that connects to the internet (typically a WAN cable)
5) Reset the ATV to factory settings
6) Change ATV DNS to 10.0.0.22
7) Reboot ATV
8) Connect he switch to the internet
9) Reboot ATV

This should show Plex icon instead of Plex icon, but will not provide access to Plex. So let's continue:

10) In your browser (Safari, Firefox, Chrome, etc) open http://10.0.0.22:81 and https://10.0.0.22:444

This will test if PlexConnect http service is working, and nginx (the Syno Web app) is passing http requests to PlexConnect

11) Parametrize timezone in the ATV (very important, in my country it is set to Los Angeles after a reset and I'm in Lisbon)
12) Load the certs

After loading certs you will be able to enter PlexConnect. You will not see any libraries. So go to Settings (rightmost part of the screen) and login to plex.tv. Now you should see that at least one Plex server was found.

**Comment by moodyblue** [comment]
You can also do step 10 after step 2 (and before step 3)

**Comment by virtualex-itv** [comment]
thanks for the detailed instructions but in my case I wouldn't be able to complete step 4 because it's a PoE switch.  If I unplug the cable, the device will lose power.

**Comment by virtualex-itv** [comment]
`:81` works but `:444` did not work.  Still same issue where posters are not loading.  Also, fan art option is unavailable.

**Comment by virtualex-itv** [comment]
@moodyblue - few days in, all is working and running stable now except for the plex icon which has never seemed to appear.  I've also noticed that there are other default ATV applications that are missing their icons as well.

**Comment by aneilbaboo** [comment]
Hi @moodyblue  @virtualex-itv  - Any chance we can get a DSM 7 version to try out? I have no idea how to build it.
